package com.tlt.georepo.modules.menu.job.request.detail.common


data class RequestDetailItem(
//
//    var aDDRESSID: String,
//    var bALLOONAMT: String,
//    var bRANCH: String,
//    var cHASISNO: String,
//    var cOLORDESC: String,
//    var cONTRACTNO: String,
//    var cONTRACTSTATUS: String,
//    var cONTRACTSTATUSDESC: String,
//    var cONTRACTTYPE: String,
//    var cONTRACTTYPEDESC: String,
//    var eNGINENO: String,
//    var hPAMT: String,
//    var iNSTALLMENTAMT: String,
//    var iNSTALLMENTDUEAMT: String,
//    var jOBID: String,
//    var lASTDUEDATE: String,
//    var lASTPAIDAMT: String,
//    var mAINID: String,
//    var mODELDESC: String,
//    var oTHERSAMT: String,
//    var oUTSTANDINGAMT: String,
//    var oVERDUEDATEFROM: String,
//    var oVERDUEDATETO: String,
//    var oVERDUEDAYS: String,
//    var oVERDUEITEM: String,
//    var oVERDUEITEMFROM: String,
//    var oVERDUEITEMTO: String,
//    var pAIDDATE: String,
//    var pAIDTOITEM: String,
//    var pAYMENTDESC: String,
//    var pAYMENTTYPE: String,
//    var pENALTYAMT: String,
//    var pENALTYDATE: String,
//    var rEGISTERNO: String,
//    var rEGISTERPROVINCE: String,
//    var tOTALOVDAMT: String,
//    var tOTALTERM: String


        var mAINID: String ,
        var jOBID: String,
        var aDDRESSID: String,
        var bRANCH: String,
        var cONTRACTNO: String,
        var rEGISTERNO: String,
        var rEGISTERPROVINCE: String,
        var cOLORDESC: String,
        var mODELDESC: String,
        var cHASISNO: String,
        var eNGINENO: String,
        var oVERDUEDAYS: String,
        var iNSTALLMENTDUEAMT: String,
        var pENALTYDATE: String,
        var pENALTYAMT: String,
        var oTHERSAMT: String,
        var tOTALOVDAMT: String,
        var cONTRACTSTATUS: String,
        var pAIDTOITEM: String,
        var pAIDDATE: String,
        var oVERDUEITEM: String,
        var oVERDUEITEMFROM: String,
        var oVERDUEDATEFROM: String,
        var oVERDUEITEMTO: String,
        var oVERDUEDATETO: String,
        var iNSTALLMENTAMT: String,
        var lASTDUEDATE: String,
        var eXPECTSUINGDATE: String
)